AllCops:
  NewCops: disable

inherit_gem:
  relaxed-rubocop: .rubocop.yml

Layout/IndentationWidth:
  Width: 4

# -- Disable footguns
Lint/UnusedMethodArgument:
  AutoCorrect: false

# -- Disable intrusive lints
Lint/UselessAssignment:
  AutoCorrect: false

Style/RedundantBegin:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/DefWithParentheses:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses

# -- Naming
Naming/MethodName:
  EnforcedStyle: camelCase

# Local variables are snake_case,
#  but instance and class variables are camelCase.
Naming/VariableName:
  EnforcedStyle: snake_case
  AllowedPatterns:
    - '^@@?[a-z]+[A-Z][a-zA-Z0-9]*$'

# There is no way to configure a custom class name pattern,
#  so just disable the check entirely.
Naming/ClassAndModuleCamelCase:
  Enabled: false

# -- Squish
# Without these settings,
#  rubocop would flag code auto-generated by squish.
Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Encoding:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/MixinUsage:
  Enabled: false
